const express = require("express");
const verifyToken = require("../middleware/verifyToken");
const CreateProfileControllers = require("../controllers/CreateProfileControllers");
const UpdateProfileControllers = require("../controllers/UpdateProfileControllers");
const GetProfileControllers = require("../controllers/GetProfileControllers");
const GetSingleProfile = require("../controllers/GetSingleProfile");
const router = express.Router();
router.post("/", verifyToken, CreateProfileControllers);
router.put("/", verifyToken, UpdateProfileControllers);
router.get("/", verifyToken, GetProfileControllers);
router.get("/:id", GetSingleProfile);
module.exports = router;
